### ISSUE TITLE
Block-oriented, primary support

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-platform#309]
This is a master issue for  The [Primary-Support project](https://github.com/orgs/mumuki/projects/8), which **MUST** be generic enough to support any block language, but targets GobstonesJr by now. 

These are are main, critical tasks:

 - [x] Implement **fully functional** laboratory layout. See:
    *  https://github.com/mumuki/mumuki-laboratory/issues/941
    *  https://github.com/mumuki/mumuki-laboratory/issues/951
    * https://github.com/mumuki/mumuki-gobstones-runner/issues/62
   - [x] Develop and integrate characters in the main situation (exercise passed, failed, passed_with_warnings, description explanation and hint) . See https://github.com/mumuki/mumuki-laboratory/issues/1015
   - [x] Implement client-level submission: Gobstones program should be executed locally and visually, step-by-step. See:
      *  https://github.com/mumuki/mumuki-gobstones-runner/issues/59,
      *  https://github.com/mumuki/mumuki-laboratory/issues/943, 
      *  https://github.com/mumuki/mumuki-gobstones-runner/issues/60, 
      * https://github.com/mumuki/mumuki-laboratory/issues/944
   - [x] Implement validation: the submission must be sent on background to the runner.    
   - [x] Implement blocks persistence: blocks and they layout should be restored after exiting and entering an exercise back. See:
       * https://github.com/mumuki/mumuki-laboratory/pull/955
       * https://github.com/mumuki/mumuki-laboratory/issues/956
- [x] Be able to create gobstones exercises from blibliotheca. See:
     *  https://github.com/mumuki/mumuki-bibliotheca/issues/123
     *  https://github.com/mumuki/mumuki-bibliotheca/issues/129
- [x] Be able to review block exercises from classroom
- [ ] Implement full support to attires in the three applications. See:
     * https://github.com/mumuki/mumuki-bibliotheca/issues/124,
     * https://github.com/mumuki/mumuki-laboratory/issues/942, 
     * https://github.com/mumuki/mumuki-gobstones-runner/issues/58
   

These are the very important but not critical tasks: 

- [x] Improve gobstones' runner responses: https://github.com/mumuki/mumuki-gobstones-runner/issues/67
- [x] Improve accessibility. See https://github.com/mumuki/mumuki-gobstones-runner/issues/57
- [ ] Improve navigation. See:
     *  https://github.com/mumuki/mumuki-laboratory/issues/952, 
     *  https://github.com/mumuki/mumuki-laboratory/issues/953, 
     *  https://github.com/mumuki/mumuki-laboratory/issues/947
- [x] Improve attires. See https://github.com/mumuki/mumuki-gobstones-runner/issues/61
- [ ] Support a characters library. See https://github.com/mumuki/mumuki-bibliotheca/issues/130

These are nice-to-have tasks:

* [ ] Improve gamification https://github.com/mumuki/mumuki-platform/issues/252

**Comment by flbulgarelli** [comment]
Closing since main tasks were solved..
